import { StyleSheet, Platform } from "react-native";
import theme, { tokens, shadows } from './theme';

const stylesMS = StyleSheet.create({
containerMCTop: {
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#ffffff',
},
titlesMC:{
    fontSize: 28,
    fontWeight: '900',
    color: '#08302E',
},
subtitlesMC:{
    fontSize: 14,
    fontWeight: '400',
    marginTop: 4,
    color: '#527F7C',
},
buttonStats:{
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#E5F2F0',
    borderWidth: 1.5,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 6,
},
textButtonMCStats:{
    fontSize: 14,
    fontWeight: '700',
    color: '#08302E',
},
searchContainerTop: {
    backgroundColor: '#F5FAF9',
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    height: 52,
    marginTop: 24,
},
searchInputTop: {
    flex: 1,
    fontSize: 15,
    color: '#08302E',
},
containerMCBottonsMain:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 30,
},
buttonCDeck: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    width: "47%",
    height: 120,
    borderRadius: 24,
    backgroundColor: '#ffffff',
    ...shadows.card,
},
buttonCFlashcard:{
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    width: "47%",
    height: 120,
    borderRadius: 24,
    backgroundColor: '#ffffff',
    ...shadows.card,
},
buttonCardText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#08302E',
},
misMazosTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#08302E',
    marginTop: 36,
    marginLeft: 20,
},
// Styles for deck cards list
deckListContainer: {
    flex: 1,
    marginTop: 16,
    paddingHorizontal: 20,
    paddingBottom: 20,
},
deckCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
},
deckCardLeft: {
    flexDirection: 'column',
    flex: 1,
},
deckTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#08302E',
},
deckCount: {
    fontSize: 14,
    color: '#527F7C',
    marginTop: 6,
    fontWeight: '500',
},
deckCardRight: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#12B5B0',
    alignItems: 'center',
    justifyContent: 'center',
},
deckCardIcon: {
    fontSize: 20,
    color: '#ffffff',
    fontWeight: '700',
},
// Modal styles
modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
},
modalContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    width: '88%',
    maxWidth: 400,
    padding: 24,
    alignItems: 'center',
    ...shadows.card,
},
modalHeaderIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#E8F5F0', // Light mint
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
},
modalTitleCenter: {
    fontSize: 24,
    fontWeight: '800',
    color: '#08302E',
    textAlign: 'center',
    marginBottom: 8,
},
modalSubtitle: {
    fontSize: 14,
    color: '#527F7C',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
},
modalLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#08302E',
    marginBottom: 8,
    alignSelf: 'flex-start',
    width: '100%',
},
modalInput: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#E5F2F0',
    borderRadius: 4,
    paddingHorizontal: 16,
    height: 52,
    fontSize: 15,
    color: '#08302E',
    backgroundColor: '#ffffff',
    marginBottom: 24,
},
modalButtonCreate: {
    width: '100%',
    height: 52,
    borderRadius: 26,
    backgroundColor: '#12B5B0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    ...Platform.select({
        ios: {
            shadowColor: '#12B5B0',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.35,
            shadowRadius: 16,
        },
        android: {
            elevation: 8,
        },
    }),
},
modalButtonTextCreate: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
},
modalButtonCancel: {
    width: '100%',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
},
modalButtonTextCancel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#08302E',
},
// Toast styles
toastContainer: {
    position: 'absolute',
    top: 0,
    left: 20,
    right: 20,
    borderRadius: tokens.radius.md,
    ...shadows.card,
    zIndex: 9999,
},
toastContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
},
toastText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    lineHeight: 20,
}
})
export default stylesMS;



