import { StyleSheet } from 'react-native';

export default function get_stylesLearningPath(theme) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
      paddingTop: 40,
    },
    headerContainer: {
      paddingHorizontal: 24,
      marginBottom: 24,
    },
    headerTitle: {
      fontSize: 32,
      fontWeight: '900',
      color: theme.colors.foreground,
      marginBottom: 6,
      letterSpacing: -0.5,
    },
    headerSubtitle: {
      fontSize: 16,
      color: theme.colors.mutedForeground,
      fontWeight: '500',
    },
    listContent: {
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    cardContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 20,
      marginBottom: 16,
      elevation: 8,
      shadowColor: theme.colors.mutedForeground,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
    },
    cardLocked: {
      backgroundColor: theme.colors.muted,
      elevation: 2,
      shadowOpacity: 0.05,
    },
    iconContainer: {
      width: 64,
      height: 64,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 18,
    },
    iconAvailable: {
      backgroundColor: theme.colors.primaryLight || theme.colors.primary,
    },
    iconLocked: {
      backgroundColor: theme.colors.muted,
    },
    textContainer: {
      flex: 1,
    },
    cardTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.colors.foreground,
      marginBottom: 4,
    },
    cardTitleLocked: {
      color: theme.colors.mutedForeground,
    },
    cardStatus: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.colors.primary,
    },
    cardStatusLocked: {
      color: theme.colors.mutedForeground,
      fontWeight: '600',
    },
    playButton: {
      backgroundColor: theme.colors.primary,
      width: 48,
      height: 48,
      borderRadius: 24,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 4,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    lockIconContainer: {
      width: 48,
      height: 48,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.muted,
      borderRadius: 24,
    },
    // Nuevos estilos para la ruta de aprendizaje
    journeyText: {
      fontSize: 14,
      fontWeight: '800',
      color: theme.colors.primary,
      letterSpacing: 1.5,
      marginBottom: 4,
    },
    titleText: {
      fontSize: 26,
      fontWeight: '900',
      color: theme.colors.foreground,
      marginBottom: 20,
    },
    progressContainer: {
      width: '100%',
      backgroundColor: theme.colors.surfaceContainerLow || '#E8F5F0',
      padding: 16,
      borderRadius: 20,
      marginBottom: 30,
    },
    progressRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    progressLabelLeft: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.foreground,
    },
    progressLabelRight: {
      fontSize: 13,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    progressBarBg: {
      height: 6,
      backgroundColor: theme.colors.border,
      borderRadius: 4,
      overflow: 'hidden',
      width: '100%',
    },
    progressBarFill: {
      height: '100%',
      backgroundColor: theme.colors.primaryLight || theme.colors.primary,
      borderRadius: 4,
    },
    pathNodeContainer: {
      width: '100%',
      alignItems: 'center',
      marginVertical: 15,
    },
    circleCompleted: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 6,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    masteredBadge: {
      position: 'absolute',
      top: -10,
      backgroundColor: '#FFD700',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
      zIndex: 1,
    },
    masteredText: {
      fontSize: 10,
      fontWeight: '900',
      color: '#000',
    },
    pillCompleted: {
      marginTop: 8,
      backgroundColor: theme.colors.primaryLight || '#E0F2F1',
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
    },
    pillCompletedText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.primary,
    },
    circleActive: {
      width: 90,
      height: 90,
      borderRadius: 45,
      backgroundColor: theme.colors.card,
      borderWidth: 4,
      borderColor: theme.colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 10,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 10,
    },
    pillActive: {
      marginTop: 8,
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 16,
      paddingVertical: 6,
      borderRadius: 15,
    },
    pillActiveText: {
      fontSize: 14,
      fontWeight: '800',
      color: '#fff',
    },
    pillContinue: {
      marginTop: 4,
    },
    pillContinueText: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.colors.primary,
      textTransform: 'uppercase',
    },
    circleLocked: {
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: theme.colors.muted,
      justifyContent: 'center',
      alignItems: 'center',
      opacity: 0.7,
    },
    pillLocked: {
      marginTop: 8,
      backgroundColor: theme.colors.muted,
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
    },
    pillLockedText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.mutedForeground,
    }
  });
}
