import { StyleSheet } from 'react-native';
import theme, { tokens, shadows } from './theme';

const stylesProfile = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.surfaceLowest || theme.colors.background,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  topBarTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: theme.colors.primaryDark || theme.colors.foreground,
  },
  header: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceContainer || theme.colors.card,
    marginHorizontal: 20,
    borderRadius: tokens.radius.lg,
    paddingVertical: 24,
    marginBottom: 20,
    marginTop: 10,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: 10,
  },
  avatarBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#F59E0B', // Amber
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  profileTitle: {
    color: theme.colors.primaryDark || theme.colors.foreground,
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 4,
  },
  pointsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  points: {
    color: theme.colors.mutedForeground,
    fontSize: 14,
    fontWeight: '500',
  },
  nameEditContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 4,
  },
  nameInput: {
    backgroundColor: theme.colors.surfaceContainerLow,
    color: theme.colors.primaryDark,
    fontSize: 24,
    fontWeight: '800',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    minWidth: 150,
    textAlign: 'center',
  },
  editIconButton: {
    padding: 5,
  },
  statsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    gap: 10,
  },
  statBox: {
    backgroundColor: theme.colors.card,
    width: '48%',
    borderRadius: tokens.radius.md,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceContainer || theme.colors.border,
    marginBottom: 5,
    ...shadows.soft,
  },
  statBoxActive: {
    backgroundColor: theme.colors.primaryLight || theme.colors.primary,
    borderColor: theme.colors.primaryLight || theme.colors.primary,
  },
  statIcon: {
    marginBottom: 8,
  },
  statLabel: {
    fontSize: 10,
    color: theme.colors.mutedForeground,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  statLabelActive: {
    color: 'rgba(255,255,255,0.8)',
  },
  statValue: {
    fontSize: 22,
    fontWeight: '800',
    color: theme.colors.primaryDark || theme.colors.foreground,
  },
  statValueActive: {
    color: '#fff',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 25,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: theme.colors.primaryDark || theme.colors.foreground,
  },
  sectionLink: {
    fontSize: 14,
    color: theme.colors.primaryLight || theme.colors.primary,
    fontWeight: '600',
  },
  achievementsList: {
    paddingHorizontal: 20,
    gap: 12,
  },
  achievementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceContainer || theme.colors.card,
    padding: 16,
    borderRadius: tokens.radius.md,
  },
  achievementIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  achievementTextContainer: {
    flex: 1,
  },
  achievementTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.primaryDark || theme.colors.foreground,
    marginBottom: 4,
  },
  achievementDesc: {
    fontSize: 12,
    color: theme.colors.mutedForeground,
    lineHeight: 16,
  },
  achievementRight: {
    marginLeft: 10,
  },
  achievementLocked: {
    opacity: 0.6,
  },
  progressContainer: {
    height: 4,
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderRadius: 2,
    marginTop: 10,
    width: '80%',
  },
  progressBar: {
    height: '100%',
    backgroundColor: theme.colors.primaryLight || theme.colors.primary,
    borderRadius: 2,
  },
  levelCard: {
    backgroundColor: theme.colors.card,
    marginHorizontal: 20,
    marginTop: 30,
    marginBottom: 20,
    padding: 24,
    borderRadius: tokens.radius.xl,
    borderWidth: 1,
    borderColor: theme.colors.surfaceContainer || theme.colors.border,
    alignItems: 'center',
    ...shadows.card,
  },
  levelHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 15,
  },
  levelTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.mutedForeground,
  },
  levelXp: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.primaryLight || theme.colors.primary,
  },
  levelProgressBg: {
    height: 10,
    backgroundColor: theme.colors.surfaceContainer || theme.colors.border,
    borderRadius: 5,
    width: '100%',
    marginBottom: 15,
  },
  levelProgressFill: {
    height: '100%',
    backgroundColor: theme.colors.primaryLight || theme.colors.primary,
    borderRadius: 5,
  },
  levelHint: {
    fontSize: 12,
    color: theme.colors.mutedForeground,
  },
  logoutContainer: {
    marginTop: 20,
    marginBottom: 40,
    paddingHorizontal: 20,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderRadius: tokens.radius.md,
    backgroundColor: theme.colors.surfaceContainer || theme.colors.card,
    gap: 10,
  },
  logoutButtonText: {
    color: theme.colors.primaryDark || theme.colors.foreground,
    fontSize: 16,
    fontWeight: '600',
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderRadius: tokens.radius.md,
    gap: 10,
    marginTop: 10,
  },
  deleteButtonText: {
    color: '#dc3545',
    fontSize: 14,
    fontWeight: '600',
  },
});

export default stylesProfile;
